//
// Created by Jlisowskyy on 7/22/24.
//

#include "../include/TunableParameters.h"

template<> GlobalParametersList* GlobalSingletonWrapper<GlobalParametersList>::_instance = nullptr;

DEFINE_TUNABLE_PARAM(int, FULL_DEPTH_FACTOR, 4);
DEFINE_TUNABLE_PARAM(int, CHECK_EXTENSION_PV_NODE, FULL_DEPTH_FACTOR::Get());
DEFINE_TUNABLE_PARAM(int, CHECK_EXTENSION, FULL_DEPTH_FACTOR::Get() / 2);
DEFINE_TUNABLE_PARAM(int, PV_EXTENSION, FULL_DEPTH_FACTOR::Get() / 2);
DEFINE_TUNABLE_PARAM(int, EVEN_EXCHANGE_EXTENSION_PV_NODE, FULL_DEPTH_FACTOR::Get());
DEFINE_TUNABLE_PARAM(int, EVEN_EXCHANGE_EXTENSION, FULL_DEPTH_FACTOR::Get() / 2);
DEFINE_TUNABLE_PARAM(int, SINGULAR_EXTENSION_DEPTH_PROBE_LIMIT, 3);
DEFINE_TUNABLE_PARAM(int, SINGULAR_EXTENSION_MIN_DEPTH, 4);
DEFINE_TUNABLE_PARAM(int, SINGULAR_EXTENSION, FULL_DEPTH_FACTOR::Get() * 2);
DEFINE_TUNABLE_PARAM(int, SINGULAR_EXTENSION_BETA_COEF, 16 / SCORE_GRAIN);
DEFINE_TUNABLE_PARAM(int, SINGULAR_EXTENSION_BETA_DIV, 1);