name: clang-format check

on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install clang-format 17
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt install clang-format-17
        sudo update-alternatives --install /usr/bin/clang-format /usr/bin/clang-format-17 100

    - name: Check clang-format version
      run: clang-format --version

    - name: Find C++ source files
      id: files-finder
      run: |
        {
          echo 'cpp_files<<EOF'
          echo $(find . -regex '.*\.\(cpp\|cc\|h\|c\)')
          echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Show found C++ files
      env:
        CPP_FILES: ${{ steps.files-finder.outputs.cpp_files}}
      run: echo "Files found $CPP_FILES"

    - name: Check formatting
      env:
        CPP_FILES: ${{ steps.files-finder.outputs.cpp_files}}
      run: |
        bash .github/workflows/clang-format-checker.sh $CPP_FILES

