name: clang-format codebase

# Run only on source code change
on: [push]

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: RafikFarhad/clang-format-github-action@v4
      with:
        sources: "**/*.h,**/*.c,**/*.cc,**/*.cpp"
        style: "file"
