name: clang-format check

on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Find C++ source files
      run: |
        echo "cpp_files<<EOF" >> $GITHUB_ENV
        find . -regex '.*\.\(cpp\|cc\|h\|c\)' -print >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Check formatting
      run: |
        ./clang-format-checker.sh
