name: clang-format check

on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Find C++ source files
      run: |
        echo "cpp_files<<EOF" >> $GITHUB_ENV
        find . -regex '.*\.\(cpp\|cc\|h\|c\)' -print >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Check formatting
      run: |
        FILES=$(cat $GITHUB_ENV | grep 'cpp_files<<EOF' -A 1 | tail -n 1)
        FORMATTING_ISSUES=0
        for FILE in $FILES; do
          DIFF_OUTPUT=$(clang-format -style=file "$FILE" | diff "$FILE" -)
          if [ -z "$DIFF_OUTPUT" ]; then
            echo "::notice::OK: $FILE is properly formatted."
          else
            echo "::error file=$FILE::NOT OK: $FILE needs formatting."
            echo "$DIFF_OUTPUT"
            FORMATTING_ISSUES=1
          fi
        done
        if [ "$FORMATTING_ISSUES" -ne 0 ]; then
          exit 1
        fi
